

server:
  servlet:
    context-path: '/university'

app:
  apiRoot: 'api/v1'

springdoc:
  swagger-ui:
    path: '/'
  api-docs:
    path: '/api-docs'

spring:
  security:
    user:
      name: user
      password: passwd
  datasource:
    url: 'jdbc:h2:mem:contractfirst-db'
#    url: 'jdbc:h2:file:/tmp/contractfirst-db'
    username: 'sa'
    driver-class-name: 'org.h2.Driver'
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.example: debug